### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by tshicelg** [dviraran/xCell#7] opened 2017-11-17 23:48 UTC
I can't get this installed.  Could you please check on this?  Thank you very much!

Tao

==================================================================
> devtools::install_github('dviraran/xCell')
Downloading GitHub repo dviraran/xCell@master
from URL https://api.github.com/repos/dviraran/xCell/zipball/master
Installing xCell
"C:/PROGRA~1/MICROS~3/ROPEN~1/R-34~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/tshi/AppData/Local/Temp/Rtmpi80SKC/devtools318022cc61b7/dviraran-xCell-0575cb2" --library="C:/Program Files/Microsoft/R Open/R-3.4.2/library" --install-tests 

Installation failed: Command failed (65535)

> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pracma_2.0.7         RevoUtils_10.0.6     RevoUtilsMath_10.0.1

loaded via a namespace (and not attached):
 [1] httr_1.2.1      compiler_3.4.2  R6_2.2.0        tools_3.4.2     withr_1.0.2     curl_2.6        memoise_1.1.0   knitr_1.15.1    git2r_0.18.0    digest_0.6.12  
[11] devtools_1.13.4 quadprog_1.5-5

**Comment by dviraran** [comment] 2017-11-19 04:51
Thanks for the notice! 

The installation works for me and other colleagues on mac, so my guess that is related to that you are using a PC. I don't have access to any PC, so I am not sure how to debug this. Please let me know if you figure this out, while I search for a way to check this issue.

Best,
Dvir

**Comment by tshicelg** [comment] 2017-11-19 18:33
Hi Dvir,

Thanks for your reply!  It works on my Mac too.  It definitely a PC issue or Microsoft R (that's I'm using on PC.  And plain vanilla R  on Mac).  Still trying to figure it out...

Tao

**Comment by tedgoldstein** [comment] 2017-11-19 18:49
HI Tao
Test to see if this is true for other devtools github projects by  running some other github install like

devtools::install_github("klutometis/roxygen”)

to see if the problem is in the base system. I see from the R devtools documentation that there is a problem


     In Windows, it's not possible to upgrade
     devtools while the package is loaded because there is an open DLL,
     which in Windows can't be overwritten. This function allows you to
     build a binary package of the development version of devtools;
     then you can restart R (so that devtools isn't loaded) and install
     the package.


It may be fixed by running
     library(devtools)
    devtools::build_github_devtools()

quit R and then restart R.

This function is especially useful for Windows users who want to upgrade their version of devtools to the development version hosted on on GitHub. In Windows, it’s not possible to upgrade devtools while the package is loaded because there is an open DLL, which in Windows can’t be overwritten. This function allows you to build a binary package of the development version of devtools; then you can restart R (so that devtools isn’t loaded) and install the package.

I don’t do Windows, so I don’t really know from my own experience. But the hanging open DLL is a problem  that Apple fixed on Mac but may not have been fixed in Windows.
Best regards,
Ted

Theodore Goldstein, Ph.D.
ICHS, UCSF



On Nov 17, 2017, at 3:48 PM, tshicelg <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't get this installed. Could you please check on this? Thank you very much!

Tao

==================================================================

devtools::install_github('dviraran/xCell')
Downloading GitHub repo dviraran/xCell@master
from URL https://api.github.com/repos/dviraran/xCell/zipball/master
Installing xCell
"C:/PROGRA1/MICROS3/ROPEN1/R-341.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL
"C:/Users/tshi/AppData/Local/Temp/Rtmpi80SKC/devtools318022cc61b7/dviraran-xCell-0575cb2" --library="C:/Program Files/Microsoft/R Open/R-3.4.2/library" --install-tests

Installation failed: Command failed (65535)

sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 LC_CTYPE=English_United States.1252 LC_MONETARY=English_United States.1252 LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats graphics grDevices utils datasets methods base

other attached packages:
[1] pracma_2.0.7 RevoUtils_10.0.6 RevoUtilsMath_10.0.1

loaded via a namespace (and not attached):
[1] httr_1.2.1 compiler_3.4.2 R6_2.2.0 tools_3.4.2 withr_1.0.2 curl_2.6 memoise_1.1.0 knitr_1.15.1 git2r_0.18.0 digest_0.6.12
[11] devtools_1.13.4 quadprog_1.5-5

**Closed** 2018-02-20 05:22 UTC

**Comment by hermidalc** [comment] 2018-07-23 17:48
In Linux this problem occurs as well.  devtools::build_github_devtools() is deprecated so I wouldn't go that route.  I found the devtools problem and solution here https://github.com/r-lib/devtools/issues/1722:

options(unzip = "internal")
devtools::install_github("dviraran/xCell")

**Comment by dviraran** [comment] 2018-07-23 19:24
Thanks. I'll add it to the README file.
